name: caller

on:
  workflow_dispatch:

jobs:
  job1: 
    uses: MarkTopping/helloworld/.github/workflows/reusable_1.yml@main
    with: 
      caller-name: "Mark"
      caller-client-id: "ffs"

  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps: 
      - run: echo ${{ needs.job1.outputs.secret-value }}
