name: caller

on:
  workflow_dispatch:

jobs:
  job1: 
    uses: MarkTopping/helloworld/.github/workflows/reusable_1.yml@main
    secrets:
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }} 
      

  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps: 
      - run: echo "hello"
