name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  IMAGE_TAG: azureimagerepo.azurecr.io/helloworldapi:$(date +%s)

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file HelloWorld.API/Dockerfile --tag ${{ env.IMAGE_TAG }}

    - name: Publish Image to ACR
      run: docker push ${{ env.IMAGE_TAG }}
