name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build-and-publish-image:

    runs-on: ubuntu-latest

    steps:
    
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@v3

    - name: 'Azure Login'
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    - name: Build Docker image
    - run: docker build . --file HelloWorld.API/Dockerfile --tag ${{ secrets.REGISTRY_LOGIN_SERVER }}/helloworldapi:${{ github.sha }}

    - name: Login to ACR
      uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
    
    - name: Publish Image to ACR
      run: docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/helloworldapi:${{ github.sha }}
