name: Run Azure Login with OpenID Connect and PowerShell
on: 
  workflow_dispatch

permissions:
  id-token: write
  contents: read
      
jobs: 
  Auth-With-Azure:
    runs-on: ubuntu-latest
    steps:
      - name: OIDC Login to Azure Public Cloud
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }} 

      - name: 'Run Azure CLI command'
        run: |
          az account show
          pwd
