name: Ex1 - 03 Deploy

run-name: Deploy Application

on:
  # Workflow can be manually triggered
  workflow_dispatch:
  # Workflow auto-triggers when Publish Image completes upon the main branch
  workflow_run:
    workflows:
      - Ex1 - 02 Publish Image
    types: 
      - completed
    branches:
      - main

jobs:
          
  deploy-to-dev:
    runs-on: ubuntu-latest
    environment: dev
    steps:
    
      - name: Deploy to Dev
        run: echo "deploying via helm"

  deploy-to-dde:
    runs-on: ubuntu-latest
    needs: [deploy-to-dev]
    environment: dde
    steps:
    
      - name: Deploy to DDE
        run: echo "deploying via helm"

  deploy-to-uat:
    # only runnable if deploying a tag
    if: ${{ startsWith(github.ref, 'refs/tags/') }}
    runs-on: ubuntu-latest
    needs: [deploy-to-dde]
    environment: uat
    steps:
    
      - name: Deploy to UAT
        run: echo "deploying via helm"

  deploy-to-prd:
    # only runnable if deploying a tag
    if: ${{ startsWith(github.ref, 'refs/tags/') }}
    runs-on: ubuntu-latest
    needs: [deploy-to-uat]
    environment: prd
    steps:
    
      - name: Deploy to PRD
        run: echo "deploying via helm"
