name: Ex1 - 01 Build on Push

run-name: Running build job

on:
  push:
    branches:
      main
      'feat/**'
      'feature/**'

  workflow_dispatch:

jobs:
  print-context:
    runs-on: ubuntu-latest
    steps:
      - env: 
          EVENT_CONTEXT: ${{ toJSON(github.event) }}
        run: |
          echo $EVENT_CONTEXT
      
  docker-build:
    runs-on: ubuntu-latest

    steps:
    
      - name: Build
        run: echo "running docker build --target=build"
