name: Ex1 - 03 Deploy

run-name: Deploy Application

on:
  workflow_dispatch

jobs:
          
  deploy-to-dev:
    runs-on: ubuntu-latest
    environment: dev
    steps:
    
      - name: Deploy to Dev
        run: echo "deploying via helm"

  deploy-to-dde:
    runs-on: ubuntu-latest
    needs: [deploy-to-dev]
    environment: dde
    steps:
    
      - name: Deploy to DDE
        run: echo "deploying via helm"

  deploy-to-uat:
    runs-on: ubuntu-latest
    needs: [deploy-to-dde]
    environment: uat
    steps:
    
      - name: Deploy to UAT
        run: echo "deploying via helm"

  deploy-to-prd:
    runs-on: ubuntu-latest
    needs: [deploy-to-uat]
    environment: prd
    steps:
    
      - name: Deploy to PRD
        run: echo "deploying via helm"
