name: Ex1 - 03 Code Scan

run-name: Running Code Scan

on:
  workflow_run:
    workflows: ["Ex1 - 02 Test"]

  workflow_dispatch:

jobs:

  print-context:
    runs-on: ubuntu-latest
    steps:
      - env: 
          EVENT_CONTEXT: ${{ toJSON(github.event) }}
        run: |
          echo $EVENT_CONTEXT
          
  run-code-scan:
    runs-on: ubuntu-latest

    steps:
    
      - name: Build
        run: echo "running Vericode code scan"
