name: Ex1 - 02 Test

on:
  workflow_run:
    workflows: ["Ex1 - 01 Build on Push"]

jobs:

  print-context:
    runs-on: ubuntu-latest
    steps:
      - env: 
          EVENT_CONTEXT: ${{ toJSON(github.event) }}
        run: |
          echo $EVENT_CONTEXT
          
  run-tests:
    runs-on: ubuntu-latest

    steps:
    
      - name: Build
        run: echo "running docker build --target=test"
