name: Ex1 - 02 Test

on:
  pull_request:
    types:
      - opened
      
  push:
    branches:
      - main
      - 'release/**'
      - 'releases/**'

jobs:

  run-tests:
    runs-on: ubuntu-latest

    steps:
    
      - name: Build
        run: echo "running docker build --target=test"
