name: Ex1 - 01 Build on Push

on:
  push:
    branches:
      main
      'feat/**'
      'feature/**'

  workflow_dispatch:

jobs:

  docker-build:
    runs-on: ubuntu-latest

    steps:
    
      - name: Build
        run: echo "running docker build --target=build"
