name: Ex1 - 02 Test

on:
  workflow_run:
    workflows: ["Ex1 - 01 Build on Push"]

jobs:

  run-tests:
    runs-on: ubuntu-latest

    steps:
    
      - name: Build
        run: echo "running docker build --target=test"
