name: ex-build-and-test

on:
  workflow_dispatch

jobs:

  docker-build:
    runs-on: ubuntu-latest

    steps:
    
      - name: Build
        run: echo "running docker build --target=build"

      - name: Test
        run: "echo running docker build --target=test"

      - name: Publish
        run: "echo running docker build --target=final"
