name: Get Secret
on: 
  workflow_dispatch

permissions:
  id-token: write
  contents: read
      
jobs: 
  Auth-With-Azure:
    runs-on: ubuntu-latest
    # environment: build
    steps:
      - name: Auth
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }} 

      - name: 'Run Azure CLI command'
        run: |
          az account show

      - name: Get Secret
        uses: Azure/get-keyvault-secrets@v1
        with:
          keyvault: "github-oidc-test-kv"
          secrets: 'example-secret'
        id: kvSecretStep
        
      - name: Use Secret
        run: echo "Secret obtaied (obfuscated):" ${{ steps.kvSecretStep.outputs.example-secret }}
