name: MR Ex1 - Seperate Jobs

run-name:  "#${{ github.run_number }}. Build and Deploy on ${{ github.ref_type }} '${{ github.ref_name }}'. Triggered by: ${{ github.triggering_actor }}"

on:
  # Allow for manual execution
  workflow_dispatch:
  # Auto trigger when pushes to selected branch naming conventions occir
  push: 
    branches: [main, feat/**, feature/**, release/**]
    paths-ignore: ['*.md']
  # Auto trigger when a release is created
  release:
    types: [published]

jobs:

  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: Build
        run: echo "running docker build --target=build"
      - name: Test
        run: echo "running docker build --target=test"

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Lint Tool
        run: echo "Setting up Lint tool"
      - name: Lint Code
        run: echo "Linting code"

  code-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Download Vericode
        run: echo "downloading Vericode"
      - name: Scan
        run: echo "scanning code"

  publish:
    runs-on: ubuntu-latest
    needs: [build-and-test, code-scan]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build Image
        run: echo "running docker build --target=final"
      - name: Download Trivy
        run: echo "downloading Trivy"
      - name: Aqua Image Scan
        run: echo "scanning image"
      - name: Login to ACR
        run: echo "logging into ACR"
      - name: Publish Image
        run: echo "publishing image with tag ???"
      - name: Logout of ACR
        run: echo "logging out of ACR"

  deploy-to-dev:
    runs-on: ubuntu-latest
    needs: [publish]
    environment: dev
    steps:
      - name: Deploy to Dev
        run: echo "deploying via helm"

  deploy-to-dde:
    runs-on: ubuntu-latest
    needs: [publish]
    environment: dde
    steps:
      - name: Deploy to DDE
        run: echo "deploying via helm"

  deploy-to-uat-weu:
    # only runnable if deploying a tag
    name: UAT West Europe
    if: ${{ startsWith(github.ref, 'refs/tags/') }}
    runs-on: ubuntu-latest
    needs: [publish, deploy-to-dde]
    environment: uat
    steps:
      - name: Deploy to UAT
        run: echo "deploying via helm"

  deploy-to-uat-neu:
    # only runnable if deploying a tag
    name: UAT North Europe
    if: ${{ startsWith(github.ref, 'refs/tags/') }}
    runs-on: ubuntu-latest
    needs: [publish, deploy-to-dde]
    environment: uat
    continue-on-error: true
    steps:
      - name: Deploy to UAT
        run: echo "deploying via helm"

  deploy-to-prd-weu:
    # only runnable if deploying a tag
    name: PRD West Europe
    if: ${{ startsWith(github.ref, 'refs/tags/') }}
    runs-on: ubuntu-latest
    needs: [publish, deploy-to-uat-weu]
    environment: prd
    steps:
      - name: Deploy to PRD
        run: echo "deploying via helm"

  deploy-to-prd-neu:
    # only runnable if deploying a tag
    name: PRD North Europe
    if: ${{ startsWith(github.ref, 'refs/tags/') }}
    runs-on: ubuntu-latest
    needs: [publish, deploy-to-uat-weu]
    environment: prd
    continue-on-error: true
    steps:
      - name: Deploy to PRD
        run: echo "deploying via helm"
