name: Ex2 - 01 Full Pipeline

run-name: Build and Deploy on ${{ github.ref }}

on:
  # Allow for manual execution
  workflow_dispatch:
  # Auto trigger when pushes to selected branch naming conventions occir
  push: 
    branches: [main, feat/**, feature/**, release/**]
  # Auto trigger when a release is created
  release:
    types: [published]

jobs:

  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: Build
        run: echo "running docker build --target=build"
      - name: Test
        run: echo "running docker build --target=test"

  code-scan:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: Download Vericode
        run: echo "downloading Vericode"
      - name: Scan
        run: echo "scanning code"

  publish:
    runs-on: ubuntu-latest
    needs: [build-and-test, code-scan]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build Image
        run: echo "running docker build --target=final"
      - name: Download Trivy
        run: echo "downloading Trivy"
      - name: Aqua Image Scan
        run: echo "scanning image"
      - name: Login to ACR
        run: echo "logging into ACR"
      - name: Publish Image
        run: echo "publishing image with tag ???"
      - name: Logout of ACR
        run: echo "logging out of ACR"

  deploy-to-dev:
    runs-on: ubuntu-latest
    needs: [publish]
    environment: dev
    steps:
      - name: Deploy to Dev
        run: echo "deploying via helm"

  deploy-to-dde:
    runs-on: ubuntu-latest
    needs: [publish]
    environment: dde
    steps:
      - name: Deploy to DDE
        run: echo "deploying via helm"

  deploy-to-uat:
    # only runnable if deploying a tag
    if: ${{ startsWith(github.ref, 'refs/tags/') }}
    runs-on: ubuntu-latest
    needs: [publish, deploy-to-dde]
    environment: uat
    steps:
      - name: Deploy to UAT
        run: echo "deploying via helm"

  deploy-to-prd:
    # only runnable if deploying a tag
    if: ${{ startsWith(github.ref, 'refs/tags/') }}
    runs-on: ubuntu-latest
    needs: [publish, deploy-to-uat]
    environment: prd
    steps:
      - name: Deploy to PRD
        run: echo "deploying via helm"
